#ifndef HY_FONT_PRIVTE_CODEC_DEF
#define HY_FONT_PRIVTE_CODEC_DEF

/////////////////////////////////////////////////////
// TABLE ENTRY
#define		TABLE_TAG_LEN		4

////////////////////////////////////////////////////
// TABLE NAME
#define CFF_DICT_OPERATOR_VERSION						0x00
#define CFF_DICT_OPERATOR_NOTICE						0x01
#define CFF_DICT_OPERATOR_FULLNAME						0x02
#define CFF_DICT_OPERATOR_FAMILYNAME					0x03
#define CFF_DICT_OPERATOR_WEIGHT						0x04
#define CFF_DICT_OPERATOR_FONTBBOX						0x05
#define CFF_DICT_OPERATOR_BLUEVALUES					0x06
#define CFF_DICT_OPERATOR_OTHERBLUES					0x07
#define CFF_DICT_OPERATOR_FAMILYBLUES					0x08
#define CFF_DICT_OPERATOR_FAMILYOTHERBLUES				0x09
#define CFF_DICT_OPERATOR_STDHW							0x0a
#define CFF_DICT_OPERATOR_STDVW							0x0b
#define CFF_DICT_OPERATOR_ESCAPE						0x0c
#define CFF_DICT_OPERATOR_UNIQUEID						0x0d
#define CFF_DICT_OPERATOR_XUID							0x0e
#define CFF_DICT_OPERATOR_CHARSET						0x0f
#define CFF_DICT_OPERATOR_ENCODING						0x10
#define CFF_DICT_OPERATOR_CHARSTRINGS					0x11
#define CFF_DICT_OPERATOR_PRIVATE						0x12
#define CFF_DICT_OPERATOR_SUBRS							0x13
#define CFF_DICT_OPERATOR_DEFAULTWIDTHX					0x14
#define CFF_DICT_OPERATOR_NOMINALWIDTHX					0x15
#define CFF_DICT_OPERATOR_SHORTINT						0x1C
#define CFF_DICT_OPERATOR_LONGINT						0x1D
#define CFF_DICT_OPERATOR_BCD							0x1E

#define CFF_DICT_OPERATOR_COPYRIGHT						0x0c00
#define CFF_DICT_OPERATOR_ISFIXEDPITCH					0x0c01
#define CFF_DICT_OPERATOR_ITALICANGLE					0x0c02
#define CFF_DICT_OPERATOR_UNDERLINEPOSITION				0x0c03
#define CFF_DICT_OPERATOR_UNDERLINETHICKNESS			0x0c04
#define CFF_DICT_OPERATOR_PAINTTYPE						0x0c05
#define CFF_DICT_OPERATOR_CHARSTRINGTYPE				0x0c06
#define CFF_DICT_OPERATOR_FONTMATRIX					0x0c07
#define CFF_DICT_OPERATOR_STROKEWIDTH					0x0c08
#define CFF_DICT_OPERATOR_BLUESCALE						0x0c09
#define CFF_DICT_OPERATOR_BLUESHIFT						0x0c0a
#define CFF_DICT_OPERATOR_BLUEFUZZ						0x0c0b
#define CFF_DICT_OPERATOR_STEMSNAPH						0x0c0c
#define CFF_DICT_OPERATOR_STEMSNAPV						0x0c0d
#define CFF_DICT_OPERATOR_FORCEBOLD 					0x0c0e
#define CFF_DICT_OPERATOR_LANGUAGEGROUP 				0x0c11
#define CFF_DICT_OPERATOR_EXPANSIONFACTOR 				0x0c12
#define CFF_DICT_OPERATOR_INITIALRANDOMSEED				0x0c13
#define CFF_DICT_OPERATOR_SYNTHETICBASE					0x0c14
#define CFF_DICT_OPERATOR_POSTSCRIPT					0x0c15
#define CFF_DICT_OPERATOR_BASEFONTNAME					0x0c16
#define CFF_DICT_OPERATOR_BASEFONTBLEND					0x0c17
#define CFF_DICT_OPERATOR_ROS							0x0c1e
#define CFF_DICT_OPERATOR_CIDFONTVERSION				0x0c1f
#define CFF_DICT_OPERATOR_CIDFONTREVISION				0x0c20
#define CFF_DICT_OPERATOR_CIDFONTTYPE					0x0c21
#define CFF_DICT_OPERATOR_CIDCOUNT						0x0c22
#define CFF_DICT_OPERATOR_UIDBASE						0x0c23
#define CFF_DICT_OPERATOR_FDARRAY						0x0c24
#define CFF_DICT_OPERATOR_FDSELECT						0x0c25
#define CFF_DICT_OPERATOR_FONTNAME						0x0c26

#define TYPE2_CHARSTING_OPERATOR_UNKNOW				0xFFFF
#define TYPE2_CHARSTING_OPERATOR_HSTEM				0x01
#define TYPE2_CHARSTING_OPERATOR_VSTEM				0x03
#define TYPE2_CHARSTING_OPERATOR_VMOVETO			0x04
#define TYPE2_CHARSTING_OPERATOR_RLINETO			0x05
#define TYPE2_CHARSTING_OPERATOR_HLINETO			0x06
#define TYPE2_CHARSTING_OPERATOR_VLINETO			0x07
#define TYPE2_CHARSTING_OPERATOR_RRCURVETO			0x08
#define TYPE2_CHARSTING_OPERATOR_CALLSUBR			0x0a
#define TYPE2_CHARSTING_OPERATOR_RETURN				0x0b
#define TYPE2_CHARSTING_OPERATOR_ESCAPE				0x0c
#define TYPE2_CHARSTING_OPERATOR_ENDCHAR			0x0e
#define TYPE2_CHARSTING_OPERATOR_HSTEMHM			0x12
#define TYPE2_CHARSTING_OPERATOR_HINTMASK			0x13
#define TYPE2_CHARSTING_OPERATOR_CNTRMASK			0x14
#define TYPE2_CHARSTING_OPERATOR_RMOVETO			0x15
#define TYPE2_CHARSTING_OPERATOR_HMOVETO			0x16
#define TYPE2_CHARSTING_OPERATOR_VSTEMHM			0x17
#define TYPE2_CHARSTING_OPERATOR_RCURVELINE			0x18
#define TYPE2_CHARSTING_OPERATOR_RLINECURVE			0x19
#define TYPE2_CHARSTING_OPERATOR_VVCURVETO			0x1a
#define TYPE2_CHARSTING_OPERATOR_HHCURVETO			0x1b
#define TYPE2_CHARSTING_OPERATOR_SHORTINT			0x1c
#define TYPE2_CHARSTING_OPERATOR_CALLGSUBR			0x1d
#define TYPE2_CHARSTING_OPERATOR_VHCURVETO			0x1e
#define TYPE2_CHARSTING_OPERATOR_HVCURVETO			0x1f


#define TYPE2_CHARSTING_OPERATOR_RESERVED0			0x0c00
#define TYPE2_CHARSTING_OPERATOR_RESERVED1			0x0c01
#define TYPE2_CHARSTING_OPERATOR_RESERVED2			0x0c02
#define TYPE2_CHARSTING_OPERATOR_AND				0x0c03
#define TYPE2_CHARSTING_OPERATOR_OR					0x0c04
#define TYPE2_CHARSTING_OPERATOR_NOT				0x0c05
#define TYPE2_CHARSTING_OPERATOR_ABS				0x0c09
#define TYPE2_CHARSTING_OPERATOR_ADD				0x0c0a
#define TYPE2_CHARSTING_OPERATOR_SUB				0x0c0b
#define TYPE2_CHARSTING_OPERATOR_DIV				0x0c0c
#define TYPE2_CHARSTING_OPERATOR_NEG				0x0c0e
#define TYPE2_CHARSTING_OPERATOR_EG					0x0c0f
#define TYPE2_CHARSTING_OPERATOR_DROP				0x0c12
#define TYPE2_CHARSTING_OPERATOR_PUT				0x0c14
#define TYPE2_CHARSTING_OPERATOR_GET				0x0c15
#define TYPE2_CHARSTING_OPERATOR_IFELSE				0x0c16
#define TYPE2_CHARSTING_OPERATOR_RANDOM				0x0c17
#define TYPE2_CHARSTING_OPERATOR_MUL				0x0c18
#define TYPE2_CHARSTING_OPERATOR_SQRT				0x0c1a
#define TYPE2_CHARSTING_OPERATOR_DUP				0x0c1b
#define TYPE2_CHARSTING_OPERATOR_EXCH				0x0c1c
#define TYPE2_CHARSTING_OPERATOR_INDEX				0x0c1d
#define TYPE2_CHARSTING_OPERATOR_ROLL				0x0c1e
#define TYPE2_CHARSTING_OPERATOR_HFLEX				0x0c22
#define TYPE2_CHARSTING_OPERATOR_FLEX				0x0c23
#define TYPE2_CHARSTING_OPERATOR_HFLEX1				0x0c24
#define TYPE2_CHARSTING_OPERATOR_FLEX1				0x0c25

#define TYPE2_ARGUMENT_STACK						48
#define	TYPE2_HINTS_NUMBER							96
#define	TYPE2_SUBER_NESTING							10
#define	TYPE2_CHARSTRING_LENGTH						65535
#define	TYPE2_MAXIMUM_SUBRS_COUNT					65535
#define	TYPE2_TRANSIENTARRAY_ELEMENTS				32

#define TYPE2_LINE_DIRECTION_0						0
#define TYPE2_LINE_DIRECTION_V						1
#define TYPE2_LINE_DIRECTION_H						2
#define TYPE2_LINE_END								1

#define TYPE2_CURVE_DIRECTION_0						0
#define TYPE2_CURVE_DIRECTION_V						1
#define TYPE2_CURVE_DIRECTION_H						2
#define TYPE2_CURVE_DIRECTION_HV					3
#define TYPE2_CURVE_DIRECTION_VH					4
#define TYPE2_CURVE_END								1

#endif 