//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 HYFontSmartShaper.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_HYFONTSMARTSHAPER_FORM      101
#define IDR_MAINFRAME                   128
#define IDR_HYFontSmartShapTYPE         130
#define IDD_FNT_SETUP_CFF_DLG           312
#define IDD_FNT_SETUP_DLG               313
#define IDD_IK_MRG_DLG                  317
#define IDD_IK_SPLT_DLG                 318
#define IDD_FNT_CVTPRM_DLG              322
#define IDR_MX_MENU                     325
#define IDD_MX_GCPY_DLG                 326
#define IDD_FNT_SVG_DLG                 328
#define IDD_MERGE_DLG                   329
#define IDD_FNT_TOTTC_DLG               330
#define IDD_FNT_SETUP_OPTION_DLG        334
#define IDD_FNT_INF_DLG                 338
#define IDD_VERIFYFNT_DLG               340
#define IDR_MENU1                       342
#define IDD_DMP_DLG                     344
#define IDD_VFNT_AXIS_DLG               346
#define IDD_FNT_SETUP_EM_DLG            350
#define IDD_FNT_MKJF_DLG                351
#define IDD_FNT_VRADH_DLG               353
#define IDD_FNT_MKVNT_DLG               355
#define IDD_FNT_MKVNT_MST_PAGE          357
#define IDD_FNT_MKVNT_AXS_PAGE          358
#define IDD_FNT_MKVNT_INSTNC_PAGE       361
#define IDD_FNT_MKVNT_FNT_PAGE          363
#define IDR_VERIFYFNT_MENU              365
#define IDD_MTTC_DLG                    367
#define ID_CHARS_COMPARE_DLG            369
#define IDD_RSTNM_DLG                   374
#define IDD_TXTCMP_DLG                  377
#define IDD_EMJ_DLG                     379
#define IDD_EXCHGCDE_DLG                381
#define IDD_CHKCHARSET_DLG              385
#define IDC_MN_CNVTR_STC                1001
#define IDC_MN_CNTRL_STC                1002
#define IDC_MN_CVTS_BTN                 1003
#define IDC_MN_CVTM_BTN                 1004
#define IDC_MN_V_SCRL                   1005
#define IDC_MN_SRC_VIEW_STC             1006
#define IDC_MN_DST_VIEW_STC             1007
#define IDC_MN_CMB_RVIEW_STC            1008
#define IDC_MN_THUMVIEW_STC             1009
#define IDC_MN_CNVTR_PRSS               1010
#define IDC_HYC_MAIN_MSGINF_STC         1011
#define IDC_MN_SEEK_EDT                 1012
#define IDC_MN_SEEK_BTN                 1013
#define IDC_MN_FNTST_BTN                1014
#define IDC_MN_CVT_STC                  1015
#define IDC_MN_DW_STC                   1016
#define IDC_MN_SEEK_STC                 1017
#define IDC_MN_SEEK_CMB                 1018
#define IDC_MN_VMTYP_CMB                1019
#define IDD_IK_MRG_IKF_BTN              1020
#define IDC_MN_VMTYP_STC                1020
#define IDC_MN_CUTM_BTN                 1021
#define IDD_IK_MRG_DEL_BTN              1023
#define IDD_IK_MRG_UP_BTN               1024
#define IDD_IK_MRG_DOWN_BTN             1025
#define IDD_IK_MRG_LST                  1026
#define IDD_IK_MRG_BTN                  1027
#define IDD_IK_MRG_CLEAR_BTN            1028
#define IDD_IK_MRG_INF_LST              1029
#define IDD_IK_SPLT_BTN                 1037
#define IDD_IK_SPLT_INF_LST             1043
#define IDD_IK_SPLT_IKF_EDT             1051
#define IDD_IK_SPLT_IKF_BTN             1052
#define IDD_IK_SPLT_TXTF_EDT            1053
#define IDD_IK_SPLT_TXTF_BTN            1054
#define IDD_IK_SPLT_LST                 1055
#define IDD_IK_SPLT_ADD_BTN             1056
#define IDD_IK_SPLT_DEL_BTN             1057
#define IDD_IK_SPORDER_CMB              1058
#define IDD_IK_SPLT_CTXT_EDT            1059
#define IDD_IK_SPLT_CTXT_BTN            1060
#define IDC_CVTPRM_TTF0_EDT             1067
#define IDC_CVTPRM_TTF1_EDT             1068
#define IDC_CVTPRM_TTF2_EDT             1069
#define IDC_CVTPRM_TTF3_EDT             1070
#define IDC_CVTPRM_TTF4_EDT             1071
#define IDC_CVTPRM_TTF5_EDT             1072
#define IDC_CVTPRM_TTF6_EDT             1073
#define IDC_CVTPRM_TTF7_EDT             1074
#define IDC_CVTPRM_TTF8_EDT             1075
#define IDC_CVTPRM_TTF9_EDT             1076
#define IDC_CVTPRM_OTF0_EDT             1077
#define IDC_CVTPRM_OTF1_EDT             1078
#define IDC_CVTPRM_OTF2_EDT             1079
#define IDC_CVTPRM_OTF3_EDT             1080
#define IDC_CVTPRM_OTF4_EDT             1081
#define IDC_CVTPRM_OTF5_EDT             1082
#define IDC_MX_BGID_EDT                 1082
#define IDC_CVTPRM_OTF6_EDT             1083
#define IDC_MX_EGID_EDT                 1083
#define IDC_CVTPRM_OTF7_EDT             1084
#define IDC_CVTPRM_OTF8_EDT             1085
#define IDC_MX_BGID_STC                 1085
#define IDC_CVTPRM_OTF9_EDT             1086
#define IDC_MX_EGID_STC                 1086
#define IDC_SVG_OPENFNT_BTN             1088
#define IDC_SVG_SAVESVG_BTN             1089
#define IDC_SVG_SAVESVG_EDT             1090
#define IDC_SVG_OPENFNT_EDT2            1091
#define IDC__TOTTC_ADD_LST              1092
#define IDC_TOTTC_OPEN_EDT              1093
#define IDC_TOTTC_OPEN_BTN              1094
#define IDC_TOTTC_MAKE_BTN              1095
#define IDC_FNT_INF_LST                 1112
#define IDC_DMP_FILENM_BTN              1126
#define IDC_DMP_FILENM_EDT              1127
#define IDC_DMP_AVAR_CHK                1128
#define IDC_DMP_BASE_CHK                1129
#define IDC_DMP_CBDT_CHK                1130
#define IDC_MJF_OPEN_BTN                1130
#define IDC_DMP_CBLC_CHK                1131
#define IDC__MJF_PRS_BTN                1131
#define IDC_DMP_CFF_CHK                 1132
#define IDC_EDIT1                       1132
#define IDC_DMP_CFF2_CHK                1133
#define IDC_MKV_MST_ACNDR_EDT           1133
#define IDC_RSTNM_NAME_EDT              1133
#define IDC_DMP_CAMP_CHK                1134
#define IDC_MKV_MST_DESCNDR_EDT         1134
#define IDC_RSTNM_DSTFNT_EDT            1134
#define IDC_DMP_COLR_CHK                1135
#define IDC_MKV_MST_TYACNDR_EDT         1135
#define IDC_DMP_CPAL_CHK                1136
#define IDC_MKV_MST_WDTH_EDT            1136
#define IDC_DMP_cvar_CHK                1137
#define IDC_MKV_MST_HGHT_EDT            1137
#define IDC_DMP_CVT_CHK                 1138
#define IDC_MKV_MST_TYDESCNDR_EDT       1138
#define IDC_DMP_DSIG_CHK                1139
#define IDC_MKV_MST_MSTNM_EDT           1139
#define IDC_DMP_EBDT_CHK                1140
#define IDC_VADH_PSNM_STC               1140
#define IDC_MKV_FNT_CHSCPYGHT_EDT       1140
#define IDC_DMP_EBLC_CHK                1141
#define IDC_MKV_FNT_ENGCPYGHT_EDT       1141
#define IDC_DMP_EBSC_CHK                1142
#define IDC_MKV_MST_MST_LST             1142
#define IDC_DMP_FPGM_CHK                1143
#define IDC_MKV_MST_ADD_BTN             1143
#define IDC_DMP_FVAR_CHK                1144
#define IDC_MKV_AXS_TAG_EDT             1144
#define IDC_MKV_MST_DEL_BTN             1144
#define IDC_DMP_GASP_CHK                1145
#define IDC_MKV_AXS_HID_CHK             1145
#define IDC_MKV_MST_UP_BTN              1145
#define IDC_DMP_GDEF_CHK                1146
#define IDC_MKV_MST_DWN_BTN             1146
#define IDC_DMP_GLYF_CHK                1147
#define IDC_MKV_MST_WGHT_EDT            1147
#define IDC_DMP_GPOS_CHK                1148
#define IDC_MKV_INSTNC_BOLD_CHK         1148
#define IDC_MKV_MST_MD_BTN              1148
#define IDC_DMP_GSUB_CHK                1149
#define IDC_MKV_INSTNC_ITLC_CHK         1149
#define IDC_DMP_GVAR_CHK                1150
#define IDC_MKV_INSTNC_WGHT_EDT         1150
#define IDC_DMP_HDMX_CHK                1151
#define IDC_MKV_INSTNC_WDTH_EDT         1151
#define IDC_DMP_HEAD_CHK                1152
#define IDC_MKV_INSTNC_INSTNC_LST       1152
#define IDC_DMP_HHEA_CHK                1153
#define IDC_MKV_INSTNC_ADD_BTN          1153
#define IDC_DMP_HMTX_CHK                1154
#define IDC_MKV_INSTNC_DEL_BTN          1154
#define IDC_DMP_HVAR_CHK                1155
#define IDC_MKV_INSTNC_UP_BTN           1155
#define IDC_DMP_JSTF_CHK                1156
#define IDC_MKV_INSTNC_DWN_BTN          1156
#define IDC_DMP_KERN_CHK                1157
#define IDC_MKV_INSTNC_STYNM_EDT        1157
#define IDC_DMP_LOCA_CHK                1158
#define IDC_MKV_INSTNC_AXWGHT_EDT       1158
#define IDC_DMP_LTSH_CHK                1159
#define IDC_MKV_INSTNC_AXWDTH_EDT       1159
#define IDC_DMP_MATH_CHK                1160
#define IDC_MKV_INSTNC_AXHGHT_EDT       1160
#define IDC_DMP_MAXP_CHK                1161
#define IDC_MKV_INSTNC_STYLINK_EDT      1161
#define IDC_DMP_MERG_CHK                1162
#define IDC_MKV_INSTNC_MDFY_BTN         1162
#define IDC_MKV_FNT_ENGFAMILY_EDT       1162
#define IDC_DMP_META_CHK                1163
#define IDC_MKV_FNT_CHSNAME_EDT         1163
#define IDC_DMP_MVAR_CHK                1164
#define IDC_MKV_FNT_PSTSCT_EDT          1164
#define IDC_DMP_NAME_CHK                1165
#define IDC_MKV_FNT_VRSN_EDT            1165
#define IDC_DMP_OS2_CHK                 1166
#define IDC_MKV_FNT_MKNAME_EDT          1166
#define IDC_DMP_PCLT_CHK                1167
#define IDC_MKV_AXS_AXS_LST             1167
#define IDC_DMP_POST_CHK                1168
#define IDC_MKV_AXS_ADD_BTN             1168
#define IDC_DMP_PREP_CHK                1169
#define IDC_MKV_AXS_DEL_BTN             1169
#define IDC_DMP_SBIX_CHK                1170
#define IDC_MKV_MST_OPNFILE_BTN         1170
#define IDC_DMP_STAT_CHK                1171
#define IDC_FNT_MKVNT_MK_BTN            1171
#define IDC_DMP_SVG_CHK                 1172
#define IDC_MKV_MST_DEFAULT_CHK         1172
#define IDC_DMP_VDMX_CHK                1173
#define IDC_MKV_MST_FILENAME_BTN        1173
#define IDC_DMP_VHEA_CHK                1174
#define IDC_MKV_INSTNC_FMMASTER_BTN     1174
#define IDC_DMP_VMTX_CHK                1175
#define IDC_LIST1                       1175
#define IDC_DMP_VORG_CHK                1176
#define IDC_MTTC_ADD_BTN                1176
#define IDC_DMP_VVAR_CHK                1177
#define IDC_MTTC_DEL_BTN                1177
#define IDC_DMP_DUMP_BTN                1178
#define IDC_MTTC_MKE_BTN                1178
#define IDC_MTTC_FNTS_LST               1179
#define IDC_CHARS_COMPARE_LST           1180
#define IDC_CHARS_COMPARE_ADD_LST       1181
#define IDC_CHARS_COMPARE_DEL_LST       1182
#define IDC_CHARS_COMPARE_MK_LST        1183
#define IDC_RSTNM_SRCFNT_BTN            1188
#define IDC_RSTNM_NAME_BTN              1189
#define IDC_RSTNM_DSTFNT_BTN            1190
#define IDC_RSTNM_SRCFNT_EDT            1191
#define IDC_RSTNM_PRS_BTN               1192
#define IDC_MMRG_FNTS_LST               1194
#define IDC_MMRG_ADD_BTN                1195
#define IDC_MRG_PRS                     1196
#define IDC_MMRG_DEL_BTN                1197
#define IDC_MMRG_UP_BTN                 1198
#define IDC_MMRG_MRG_BTN                1199
#define IDC_TCMPFL2_RD                  1199
#define IDC_MMRG_DWN_BTN                1200
#define IDC_TCMPFL2_BTN                 1200
#define IDC_TCMPFL1_BTN                 1201
#define IDC_TCMPZB_RD                   1202
#define IDC_TCMPMB_RD                   1203
#define IDC_TCMPNB_RD                   1204
#define IDC_TCMPDST_BTN                 1205
#define IDC_TCMPFL1_RD                  1206
#define IDC_EMJ_CNGFILE_BTN             1208
#define IDC_EMJ_CNGFILE_EDIT            1209
#define IDC_EMJ_CDEFILE_EDIT            1210
#define IDC_EMJ_CDEFILE_BTN             1211
#define IDC_EMJ_MK_BTN                  1212
#define IDC_EMJ_HMFILE_EDIT             1213
#define IDC_EMJ_HMEFILE_BTN             1214
#define IDC_CCST_CMB_LST01              1220
#define IDC_CCST_CMB_LST02              1221
#define IDC_CCST_CHK_BTN                1223
#define IDC_CCST_EXPT_BTN               1224
#define IDC_CCST_LST_CHKVEW             1229
#define IDC_PTN_SETADW_EDT              1230
#define IDC_TSC_ISCIDY_RAD              1235
#define IDC_TSC_ISCIDN_RAD              1236
#define IDC_TSC_RGST_EDIT               1237
#define IDC_TSC_ORDER_EDIT              1238
#define IDC_TSC_SUPPLE_EDIT             1239
#define IDC_TSC_SUPPLE_STC              1240
#define IDC_MN_CVT_TTF_RD               2000
#define IDC_MN_CVT_OTF_RD               2001
#define IDC_MN_PT_CHK                   2100
#define IDC_MN_PTN_CHK                  2101
#define IDC_MN_LN_CHK                   2102
#define IDC_MN_RFRLN_CHK                2103
#define IDC_MN_FL_CHK                   2104
#define IDC_TSTEM_HD_EM_EDT             2401
#define IDC_TSTEM_OS_TYDSD_EDT          2420
#define IDC_TSTEM_OS_TYASD_EDT          2421
#define IDC_TSTEM_OS_CPR1_EDT           2425
#define IDC_TSTEM_OS_CPR2_EDT           2426
#define IDC_TSTEM_OS_WEIGHT_EDT         2432
#define IDC_TSTEM_OS_WIDTH_EDT          2433
#define ID_FNT_VADH                     2500
#define IDC_VADH_SFNT_EDT               2501
#define IDC_VADH_SFNT_BTN               2502
#define IDC_VADH_PSNM_EDT               2503
#define IDC_VADH_PSNM_BTN               2504
#define IDC_VADH_PSNM_CHK               2505
#define IDC_VADH_BUDL_BTN               2506
#define IDC_VADH_TSB_EDT                2507
#define IDC_PTN_VERT_CHK                2600
#define IDC_PTN_PSNM_CHK                2601
#define IDC_PTN_SRTUNI_CHK              2602
#define IDC_PTN_YITIZI_CHK              2603
#define IDC_PTN_RMRPPNT_CHK             2604
#define IDC_PTN_CORRECT_CHK             2605
#define IDC_PTN_CMP_CHK                 2607
#define IDC_PTN_SETADW_CHK              2608
#define IDC_PTN_LYT_CHK                 2610
#define IDC_PTN_HYSND_CHK               2611
#define IDC_PTN_KANGXI_CHK              2612
#define IDC_PTN_RENAME_CHK              2614
#define IDC_PTN_CHS_EDT                 2615
#define IDC_PTN_ENG_EDT                 2616
#define IDC_PTN_CHSSUB_EDT              2617
#define IDC_PTN_ENGSUB_EDT              2618
#define IDC_PTN_VER_EDT                 2619
#define IDC_PTN_OLDSTND_CHK             2620
#define IDC_PTN_DELOLD_CHK              2621
#define IDC_MRG_SRC1_EDT                3101
#define IDC_MRG_SRC2_EDT                3102
#define IDC_MRG_DST_EDT                 3103
#define IDC_MRG_SRC1_BTN                3104
#define IDC_MRG_SRC2_BTN                3105
#define IDC_MRG_DST_BTN                 3106
#define IDC_MGR_MERGE_BTN               3107
#define IDC_MRG_SRC2TXT_EDT             3108
#define IDC_MRG_SRC2TXT_BTN             3110
#define IDC_MMRG_SRC2TXT_BTN            3111
#define IDC_MMRG_SRC2TXT_EDT            3112
#define IDC_EXCHGCDE_FUL_RD             3200
#define IDC_EXCHGCDE_DEL_RD             3201
#define IDC_EXCHGCDE_EXCHG_RD           3202
#define IDC_EXCHGCDE_FNT_EDT            3203
#define IDC_EXCHGCDE_FNT_BTN            3204
#define IDC_EXCHGCDE_CDE_EDT            3205
#define IDC_EXCHGCDE_CDE_BTN            3206
#define IDC_EXCHGCDE_SVFNT_EDT          3207
#define IDC_EXCHGCDE_SVFNT_BTN          3208
#define IDC_EXCHGCDE_RUN_BTN            3209
#define IDS_NAME_ID_0_EN                10000
#define IDS_NAME_ID_0_CHS               10001
#define IDS_NAME_ID_8_EN                10002
#define IDS_NAME_ID_8_CHS               10003
#define IDS_NAME_ID_11                  10004
#define IDS_NAME_ID_13_CHS              10005
#define IDS_NAME_ID_13_EN               10006
#define IDS_NAME_ID_14                  10007
#define IDS_NAME_ID_7_EN                10008
#define IDS_NAME_ID_7_CHS               10009
#define IDS_CHARSET_GBL1                10010
#define IDS_CHARSET_GBL2                10011
#define IDS_CHARSET_GBL3                10012
#define IDS_CHARSET_GBSYMB              10013
#define IDS_CHARSET_UniCJK              10014
#define IDS_CHARSET_UniCJKA             10015
#define IDS_CHARSET_UniCJKB             10016
#define IDS_CHARSET_UniCJKC             10017
#define IDS_CHARSET_UniCJKD             10018
#define IDS_CHARSET_UniCJKE             10019
#define IDS_CHARSET_UniCJKF             10020
#define IDS_CHARSET_UniCJKG             10021
#define IDS_CHARSET_UniCJKH             10022
#define IDS_CHARSET_UniCJKI             10023
#define IDS_CHARSET_UniKangXiRdl        10024
#define IDS_CHARSET_UniStroke           10025
#define IDS_CHARSET_UniRdlSupp          10026
#define IDS_CHARSET_UniCJKCMPT          10027
#define IDS_CHARSET_UniCJKCMPTSUPP      10028
#define IDS_CHARSET_GB                  10029
#define IDS_CHARSET_UNI                 10030
#define ID_FNT_ENCODE_PARAM             32772
#define ID_IK_MERGE                     32779
#define ID_IK_SPLIT                     32780
#define ID_FNT_MERGE                    32784
#define ID_FNT_CVTPRAM_MU               32787
#define ID_XML_CVT_MU                   32790
#define ID_MX_OPNFONT                   32793
#define ID_MX_CLSFONT                   32794
#define ID_EMOJI_EXPORT                 32799
#define ID_SVG_CVT_MU                   32801
#define ID_SVG_EOT_MU                   32803
#define ID_TO_WOFF_MU                   32816
#define ID_CHA_CONVERT                  32820
#define ID_FLNM2CDNM                    32829
#define ID_CDNM2FLNM                    32830
#define ID_MN_FNTINF                    32833
#define ID_VARIATION_MN                 32840
#define ID_MN_CHA                       32843
#define ID_MN_MKJF                      32848
#define ID_MN_CODEDOT                   32851
#define ID_MN_ADUNI                     32858
#define ID_MKVNT_MN                     32860
#define ID_MN_JSZ_CODETCHAR             32863
#define ID_32868                        32868
#define ID_32869                        32869
#define ID_32870                        32870
#define ID_VERIFYVNT_MN                 32873
#define ID_TTC_TTCTOFONT                32874
#define ID_TTC_FONTTOTTC                32875
#define ID_FNT_EXTRCD                   32880
#define ID_FNT_EXTRCHR                  32881
#define ID_FNT_EXTRNAME                 32883
#define ID_NOBOX_MNU                    32890
#define ID_FNT_RSETNAME                 32895
#define ID_MN_EXPTNAME                  32897
#define ID_FLNM2NUMNM                   32899
#define ID_MN_CMPTXT                    32901
#define ID_FILE_NEW1                    32902
#define ID_MN_CHKERTTF                  32906
#define ID_MN_CHKEROTF                  32907
#define ID_EMOJI_MK                     32910
#define ID_MN_CODEMAP                   32912
#define ID_FNT_CLEARCODE                32915
#define ID_FNT_BUDCIDOTF                32917
#define ID_G3FX_MN                      32922
#define ID_MN_CHKCHARSET                32924
#define ID_Menu                         32925
#define ID_MN_EXPNAME                   32926

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        391
#define _APS_NEXT_COMMAND_VALUE         32927
#define _APS_NEXT_CONTROL_VALUE         1231
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
