#ifndef		HY_ERROR_DEF_H
#define		HY_ERROR_DEF_H


///////////////////////////////////////////////////////////////////////////////
// ERROR Type
#define		HY_NOERROR										0x0000
#define		HY_ERR_BASE 									0x1000
#define		HY_ERR_FILE_NOEXIST 							HY_ERR_BASE+0x01
#define		HY_ERR_FILE_OPEN 								HY_ERR_BASE+0x02
#define		HY_ERR_FILE_READ 								HY_ERR_BASE+0x03
#define		HY_ERR_FILE_WRITE 								HY_ERR_BASE+0x04
#define		HY_ERR_FILE_EXIST 								HY_ERR_BASE+0x05
#define		HY_ERR_FILE_ZERO 								HY_ERR_BASE+0x06
#define		HY_ERR_FILE_STAT 								HY_ERR_BASE+0x07
#define		HY_ERR_FILE_OTHER 								HY_ERR_BASE+0x08
#define		HY_ERR_POINT_NULL								HY_ERR_BASE+0x09 
#define		HY_ERR_HANDLE_NULL								HY_ERR_BASE+0x0A 
#define		HY_ERR_FUNC_PARA								HY_ERR_BASE+0x0B
#define		HY_ERR_FILE_CHA_READ 							HY_ERR_BASE+0x0C
#define		HY_ERR_FILE_CHA_WRITE							HY_ERR_BASE+0x0D
#define		HY_ERR_UNKNOW									0xFFFFFFFF

#define		FONT_ERR_BASE									0x2000
#define		FONT_ERR_CMAP_DECODE							FONT_ERR_BASE + 0x01
#define		FONT_ERR_CMAP_ENCODE							FONT_ERR_BASE + 0x02
#define		FONT_ERR_GLYF_DECODE							FONT_ERR_BASE + 0x03
#define		FONT_ERR_GLYF_ENCODE							FONT_ERR_BASE + 0x04
#define		FONT_ERR_HEAD_DECODE							FONT_ERR_BASE + 0x05
#define		FONT_ERR_HEAD_ENCODE							FONT_ERR_BASE + 0x06
#define		FONT_ERR_HHEA_DECODE							FONT_ERR_BASE + 0x07
#define		FONT_ERR_HHEA_ENCODE							FONT_ERR_BASE + 0x08
#define		FONT_ERR_HMTX_DECODE							FONT_ERR_BASE + 0x09
#define		FONT_ERR_HMTX_ENCODE							FONT_ERR_BASE + 0x0A
#define		FONT_ERR_LOCA_DECODE							FONT_ERR_BASE + 0x0B
#define		FONT_ERR_LOCA_ENCODE							FONT_ERR_BASE + 0x0C
#define		FONT_ERR_MAXP_DECODE							FONT_ERR_BASE + 0x0D
#define		FONT_ERR_MAXP_ENCODE							FONT_ERR_BASE + 0x0E
#define		FONT_ERR_NAME_DECODE							FONT_ERR_BASE + 0x0F
#define		FONT_ERR_NAME_ENCODE							FONT_ERR_BASE + 0x10
#define		FONT_ERR_POST_DECODE							FONT_ERR_BASE + 0x11
#define		FONT_ERR_POST_ENCODE							FONT_ERR_BASE + 0x12
#define		FONT_ERR_OS2_DECODE								FONT_ERR_BASE + 0x13
#define		FONT_ERR_OS2_ENCODE								FONT_ERR_BASE + 0x14
#define		FONT_ERR_LTSH_DECODE							FONT_ERR_BASE + 0x15
#define		FONT_ERR_LTSH_ENCODE							FONT_ERR_BASE + 0x16
#define		FONT_ERR_VDMX_DECODE							FONT_ERR_BASE + 0x17
#define		FONT_ERR_VDMX_ENCODE							FONT_ERR_BASE + 0x18
#define		FONT_ERR_CVT_DECODE								FONT_ERR_BASE + 0x19
#define		FONT_ERR_CVT_ENCODE								FONT_ERR_BASE + 0x1A
#define		FONT_ERR_FPGM_DECODE							FONT_ERR_BASE + 0x1B
#define		FONT_ERR_FPGM_ENCODE							FONT_ERR_BASE + 0x1C
#define		FONT_ERR_GASP_DECODE							FONT_ERR_BASE + 0x1D
#define		FONT_ERR_GASP_ENCODE							FONT_ERR_BASE + 0x1E
#define		FONT_ERR_HDMX_DECODE							FONT_ERR_BASE + 0x1F
#define		FONT_ERR_HDMX_ENCODE							FONT_ERR_BASE + 0x20
#define		FONT_ERR_PREP_DECODE							FONT_ERR_BASE + 0x21
#define		FONT_ERR_PREP_ENCODE							FONT_ERR_BASE + 0x22
#define		FONT_ERR_DSIG_DECODE							FONT_ERR_BASE + 0x23
#define		FONT_ERR_DSIG_ENCODE							FONT_ERR_BASE + 0x24
#define		FONT_ERR_VHEA_DECODE							FONT_ERR_BASE + 0x25
#define		FONT_ERR_VHEA_ENCODE							FONT_ERR_BASE + 0x26
#define		FONT_ERR_VMTX_DECODE							FONT_ERR_BASE + 0x27
#define		FONT_ERR_VMTX_ENCODE							FONT_ERR_BASE + 0x28
#define		FONT_ERR_CFF_DECODE								FONT_ERR_BASE + 0x29
#define		FONT_ERR_CFF_ENCODE								FONT_ERR_BASE + 0x2A
#define		FONT_ERR_GSUB_DECODE							FONT_ERR_BASE + 0x2B
#define		FONT_ERR_GSUB_ENCODE							FONT_ERR_BASE + 0x2C
#define		FONT_ERR_CBLC_DECODE							FONT_ERR_BASE + 0x2D
#define		FONT_ERR_CBLC_ENCODE							FONT_ERR_BASE + 0x2E
#define		FONT_ERR_CBDT_DECODE							FONT_ERR_BASE + 0x2F
#define		FONT_ERR_CBDT_ENCODE							FONT_ERR_BASE + 0x30
#define		FONT_ERR_SBIX_DECODE							FONT_ERR_BASE + 0x31
#define		FONT_ERR_SBIX_ENCODE							FONT_ERR_BASE + 0x32
#define		FONT_ERR_FVAR_DECODE							FONT_ERR_BASE + 0x33
#define		FONT_ERR_FVAR_ENCODE							FONT_ERR_BASE + 0x34
#define		FONT_ERR_GVAR_DECODE							FONT_ERR_BASE + 0x35
#define		FONT_ERR_GVAR_ENCODE							FONT_ERR_BASE + 0x36
#define		FONT_ERR_VORG_DECODE							FONT_ERR_BASE + 0x37
#define		FONT_ERR_VORG_ENCODE							FONT_ERR_BASE + 0x38
#define		FONT_ERR_STAT_DECODE							FONT_ERR_BASE + 0x39
#define		FONT_ERR_STAT_ENCODE							FONT_ERR_BASE + 0x3A
#define		FONT_ERR_CPAL_DECODE							FONT_ERR_BASE + 0x3B
#define		FONT_ERR_CPAL_ENCODE							FONT_ERR_BASE + 0x3C
#define		FONT_ERR_COLR_DECODE							FONT_ERR_BASE + 0x3D
#define		FONT_ERR_COLR_ENCODE							FONT_ERR_BASE + 0x3E
#define		FONT_ERR_AVAR_DECODE							FONT_ERR_BASE + 0x3F
#define		FONT_ERR_AVAR_ENCODE							FONT_ERR_BASE + 0x40
#define		FONT_ERR_HVAR_DECODE							FONT_ERR_BASE + 0x41
#define		FONT_ERR_HVAR_ENCODE							FONT_ERR_BASE + 0x42
#define		FONT_ERR_VVAR_DECODE							FONT_ERR_BASE + 0x43
#define		FONT_ERR_VVAR_ENCODE							FONT_ERR_BASE + 0x44
#define		FONT_ERR_SVG_DECODE								FONT_ERR_BASE + 0x45
#define		FONT_ERR_SVG_ENCODE								FONT_ERR_BASE + 0x46
#define		FONT_ERR_EBLC_DECODE							FONT_ERR_BASE + 0x47
#define		FONT_ERR_EBLC_ENCODE							FONT_ERR_BASE + 0x48
#define		FONT_ERR_EBDT_DECODE							FONT_ERR_BASE + 0x49
#define		FONT_ERR_EBDT_ENCODE							FONT_ERR_BASE + 0x4A
#define		FONT_ERR_GPOS_DECODE							FONT_ERR_BASE + 0x4B
#define		FONT_ERR_GPOS_ENCODE							FONT_ERR_BASE + 0x4C

#define		FONT_ERR_DIRECTORY_DECODE						FONT_ERR_BASE + 0x50
#define		FONT_ERR_DIRECTORY_ENCODE						FONT_ERR_BASE + 0x51
#define		FONT_ERR_NO_TTF									FONT_ERR_BASE + 0x60
#define		FONT_ERR_NO_CFF									FONT_ERR_BASE + 0x61
#define		FONT_ERR_NO_TTC									FONT_ERR_BASE + 0x62
#define		FONT_ERR_EOT_ENCODE								FONT_ERR_BASE + 0x70
#define		FONT_ERR_SETCHECKSUM							FONT_ERR_BASE + 0x90

#define		IK_ERR_BASE										0x3000
#define		IK_ERR_CHAR_NOEXIST								0x3001
#define		IK_ERR_CHAR_REPEAT								0x3002
#define		IK_ERR_CHAR_OVERLOW								0x3003

#define		WOFF_ERR_BASE									0x4000
#define		WOFF_ERR_DECODE									0x4001
#define		WOFF_ERR_ENCODE									0x4002


#endif